repos:
  - repo: https://github.com/LiquidFun/aoc_tiles
    rev: 0.7.0
    hooks:
      - id: aoc-tiles
        args:
          - --theme=aoc
          - --animation=snow
          - --language-sorting=cpp
          - --tile-width-px=203px
          - --overwrite-year=2025
          - --auto-add-tiles-to-git=add
