repos:
  - repo: https://github.com/LiquidFun/aoc_tiles
    rev: 0.7.0
    hooks:
      - id: aoc-tiles
        args:
          - --title="ðŸŽ„ AOC 2025 â€” Progress" 
          - --auto-add-tiles-to-git=add 
          - --language-sorting=cpp
          - --overwrite-year=2025
          - --theme=aoc
          - --accent-color="#7ab7ff"
          - --animation=snow