repos:
  - repo: https://github.com/LiquidFun/aoc_tiles
    rev: 0.7.0
    hooks:
      - id: aoc-tiles
        args:
          - --theme=aoc
          - --animation=snow
          - --title="Advent of Code 2025 â€” C++"
          - --language-sorting=cpp
          - --text-color=#32C42F
          - --outline-color=#000000
          - --tile-width-px=270px
          - --overwrite-year=2025
          - --auto-add-tiles-to-git=add
